#!/bin/bash 
notify=$1
#
{
    python3 tune.py >status.txt 2>error.txt &
} || {

    /share/apps/Python-3.6.8/bin/python3.6 tune.py >status.txt 2>error.txt &
}
pid=$!
echo $pid
if [ "$notify" = "1" ]; then
    read -sp 'Password: ' password
    
    {
	python3 notifyWhenFinished.py $password $pid &
    } || {

	/share/apps/Python-3.6.8/bin/python3.6 notifyWhenFinished.py $password $pid &
    }

    
fi
