#!/bin/bash 
notify=$1
#
if ! python3 tune.py >status.txt 2>error.txt & ; then
    /share/apps/Python-3.6.8/bin/python3.6 tune.py >status.txt 2>error.txt &
fi
pid=$!
echo $pid
if [ "$notify" = "1" ]; then
    read -sp 'Password: ' password
    
    if ! python3 notifyWhenFinished.py $password $pid & ; then
	/share/apps/Python-3.6.8/bin/python3.6 notifyWhenFinished.py $password $pid &
    fi

    
fi
